SET GLOBAL time_zone = '-3:00';
DROP DATABASE IF EXISTS fitness_db;
CREATE DATABASE fitness_db DEFAULT CHARACTER SET UTF8MB4;

USE fitness_db;
DROP TABLE IF EXISTS user, service, membership, program, exercise, assigned_service, assigned_exercise;

CREATE TABLE user (
	id BIGINT NOT NULL AUTO_INCREMENT,
	login VARCHAR(50) NOT NULL UNIQUE CHECK(login !=''),
	password VARCHAR(50) NOT NULL CHECK(password !=''),
	role ENUM('ADMIN', 'CLIENT', 'INSTRUCTOR') NOT NULL,
    discount DECIMAL(3,2),
	PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE service (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
	price DECIMAL(6,2) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE membership (
	id BIGINT NOT NULL AUTO_INCREMENT,
	client_id BIGINT NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	PRIMARY KEY (id),
    FOREIGN KEY (client_id) 
    REFERENCES user (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;


CREATE TABLE program (
	id BIGINT NOT NULL AUTO_INCREMENT,
	instructor_id BIGINT NOT NULL,
	client_id BIGINT NOT NULL,
	status ENUM('AWAITING_CLIENT_ANSWER', 'ACTIVE', 'DECLINED') NOT NULL,
	PRIMARY KEY (id),
    FOREIGN KEY (instructor_id) 
    REFERENCES user (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
    FOREIGN KEY (client_id)
    REFERENCES user (id)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE exercise (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE assigned_service (
	id BIGINT NOT NULL AUTO_INCREMENT,
	service_id BIGINT NOT NULL,
	client_id BIGINT NOT NULL,
    status ENUM('AWAITING_PAYMENT', 'PAYMENT_RECEIVED') NOT NULL,
	PRIMARY KEY (id),
    FOREIGN KEY (service_id) 
    REFERENCES service (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
    FOREIGN KEY (client_id)
    REFERENCES user (id)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE assigned_exercise (
	exercise_id BIGINT NOT NULL,
	program_id BIGINT NOT NULL,
    FOREIGN KEY (exercise_id) 
    REFERENCES exercise (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
    FOREIGN KEY (program_id)
    REFERENCES program (id)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;