SET GLOBAL time_zone = '-3:00';
DROP DATABASE IF EXISTS fitness_db;
CREATE DATABASE fitness_db DEFAULT CHARACTER SET UTF8MB4;

USE fitness_db;
DROP TABLE IF EXISTS user, membership, program, exercise, assigned_service, assigned_exercise;

CREATE TABLE user (
	id BIGINT NOT NULL AUTO_INCREMENT,
	login VARCHAR(50) NOT NULL UNIQUE CHECK(login !=''),
	password VARCHAR(50) NOT NULL CHECK(password !=''),
	role ENUM('ADMIN', 'CLIENT', 'INSTRUCTOR') NOT NULL,
    discount INT(2),
	PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE membership (
	id BIGINT NOT NULL AUTO_INCREMENT,
	client_id BIGINT NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,
    payment_date DATE,
	PRIMARY KEY (id),
    FOREIGN KEY (client_id) 
    REFERENCES user (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE program (
	id BIGINT NOT NULL AUTO_INCREMENT,
	instructor_id BIGINT NOT NULL,
	client_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	status ENUM('AWAITING_CLIENT_ANSWER', 'ACTIVE', 'DECLINED') NOT NULL,
	PRIMARY KEY (id),
    FOREIGN KEY (instructor_id) 
    REFERENCES user (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
    FOREIGN KEY (client_id)
    REFERENCES user (id)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE exercise (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE assigned_exercise (
	id BIGINT NOT NULL AUTO_INCREMENT,
	program_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (exercise_id) 
    REFERENCES exercise (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
    FOREIGN KEY (program_id)
    REFERENCES program (id)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE diet (
	id BIGINT NOT NULL AUTO_INCREMENT,
	instructor_id BIGINT NOT NULL,
	client_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	status ENUM('AWAITING_CLIENT_ANSWER', 'ACTIVE', 'DECLINED') NOT NULL,
	PRIMARY KEY (id),
    FOREIGN KEY (instructor_id) 
    REFERENCES user (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
    FOREIGN KEY (client_id)
    REFERENCES user (id)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE dish (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
    meal ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK') NOT NULL,
	PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE assigned_dish (
	id BIGINT NOT NULL AUTO_INCREMENT,
	diet_id BIGINT NOT NULL,
	dish_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (diet_id) 
    REFERENCES diet (id)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
    FOREIGN KEY (dish_id)
    REFERENCES dish (id)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8MB4;